#!/usr/bin/env node
// Stage a package for one release channel, build it, and (optionally) publish it to ClawHub.
//
//   node scripts/stage.mjs work preview 5.0.0-preview.1            # stage + build + validate + dry run
//   node scripts/stage.mjs work preview 5.0.0-preview.1 --publish  # ...and publish
//
// Preview and production differ only in identity: plugin id, display name and npm package name.
// The staged copy lives in .stage/ (gitignored) inside the repository, so the workspace's
// node_modules still resolve. The source tree is never edited.
import {
	cpSync,
	existsSync,
	mkdirSync,
	readFileSync,
	rmSync,
	symlinkSync,
	writeFileSync
} from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const [pkgName, channel, version, ...flags] = process.argv.slice(2);
const publish = flags.includes('--publish');
const IDENTITIES = {
	work: {
		production: { id: 'falcon-work', name: 'Falcon Work', npm: '@fdsouvenir/falcon-work' },
		preview: {
			id: 'falcon-work-preview',
			name: 'Falcon Work Preview',
			npm: '@fdsouvenir/falcon-work-preview'
		}
	}
};
const identity = IDENTITIES[pkgName]?.[channel];
if (!identity || !/^\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$/.test(version ?? '')) {
	console.error('Usage: stage.mjs <work> <preview|production> <semver> [--publish]');
	process.exit(2);
}
if (channel === 'production' && version.includes('-')) {
	console.error('Production versions have no pre-release suffix');
	process.exit(2);
}

const run = (cmd, args, cwd, env = {}) =>
	execFileSync(cmd, args, { cwd, stdio: 'inherit', env: { ...process.env, ...env } });
const out = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, encoding: 'utf8' }).trim();

if (out('git', ['status', '--porcelain', '--untracked-files=no'], root)) {
	console.error('Commit your changes first: a release is built from a clean, pushed commit.');
	process.exit(1);
}
const commit = out('git', ['rev-parse', 'HEAD'], root);

const source = path.join(root, 'packages', pkgName);
const stage = path.join(root, '.stage', identity.id);
rmSync(stage, { recursive: true, force: true });
mkdirSync(stage, { recursive: true });
cpSync(source, stage, {
	recursive: true,
	filter: (p) => !/(^|\/)(node_modules|dist|seed)(\/|$)/.test(path.relative(source, p))
});

// The package's own dependencies (npm may not hoist them to the workspace root).
if (existsSync(path.join(source, 'node_modules')))
	symlinkSync(path.join(source, 'node_modules'), path.join(stage, 'node_modules'), 'dir');

// Identity: one source constant, the npm package, and the manifest.
writeFileSync(
	path.join(stage, 'src', 'identity.ts'),
	`// Staged for the ${channel} channel by scripts/stage.mjs.\nexport const PLUGIN_ID = '${identity.id}';\n`
);
const pkg = JSON.parse(readFileSync(path.join(stage, 'package.json'), 'utf8'));
Object.assign(pkg, { name: identity.npm, version });
writeFileSync(path.join(stage, 'package.json'), JSON.stringify(pkg, null, '\t') + '\n');
const manifestPath = path.join(stage, 'openclaw.plugin.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
Object.assign(manifest, { id: identity.id, name: identity.name, version });
delete manifest.controlUi; // regenerated by the build
const readmePath = path.join(stage, 'README.md');
if (existsSync(readmePath))
	writeFileSync(
		readmePath,
		readFileSync(readmePath, 'utf8')
			.replaceAll(IDENTITIES[pkgName].production.npm + '\n', identity.npm + '\n')
			.replace(/^# .*$/m, `# ${identity.name}`)
			.replaceAll('`falcon-work/work.db`', `\`${identity.id}/work.db\``)
			.replaceAll('`falcon-work/`', `\`${identity.id}/\``)
			.replaceAll('plugins.entries.falcon-work.', `plugins.entries.${identity.id}.`) +
			(channel === 'preview'
				? `\n> This is the **preview** channel: early builds for testing. Production is \`${IDENTITIES[pkgName].production.npm}\`.\n`
				: '')
	);
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

run('npx', ['tsc', '-p', 'tsconfig.json'], stage);
run('npx', ['openclaw', 'plugins', 'build'], stage, {
	OPENCLAW_STATE_DIR: path.join(root, '.openclaw-build')
});
run('npx', ['openclaw', 'plugins', 'validate', '--json'], stage, {
	OPENCLAW_STATE_DIR: path.join(root, '.openclaw-build')
});

const args = [
	'package',
	'publish',
	stage,
	'--family',
	'code-plugin',
	'--name',
	identity.npm,
	'--display-name',
	identity.name,
	'--version',
	version,
	'--source-repo',
	'fdsouvenir/falcon-suite',
	'--source-commit',
	commit,
	'--source-path',
	`packages/${pkgName}`,
	// Each channel is its own listing, so its newest release is that listing's `latest`;
	// without it the listing's own install command does not resolve.
	'--tags',
	'latest'
];
run('clawhub', [...args, '--dry-run'], root);
// --wait: a release only exists once ClawHub's security scan finishes; without waiting, a
// submission can sit unpublished with no way to see it.
if (publish) run('clawhub', [...args, '--wait', '--wait-timeout', '1200'], root);
else console.log('\nDry run only. Re-run with --publish to publish.');
